import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';

const out=process.argv[2];
if(!out)throw Error('Output directory required');
const wb=Workbook.create(),names=['Dashboard','Randevular','Müşteriler','Finans','Ayarlar','Hızlı Başlangıç'];
const sheets=Object.fromEntries(names.map(n=>[n,wb.worksheets.add(n)]));
const navy='#0F1B3D',orange='#FF6B35',light='#E9ECF3';
for(const sh of Object.values(sheets)){sh.showGridLines=false;sh.getRange('A1:H26').format.font={name:'Arial',size:11,color:navy};sh.getRange('A1:H26').format.rowHeight=25;sh.getRange('A1:H26').format.verticalAlignment='center';}
function head(sh,range){sh.getRange(range).format={fill:navy,font:{name:'Arial',size:11,bold:true,color:'#FFFFFF'},rowHeight:32,verticalAlignment:'center',horizontalAlignment:'center',wrapText:true};}
function table(name,headers,widths,tableName){const sh=sheets[name],last=String.fromCharCode(64+headers.length);sh.getRange(`A1:${last}1`).values=[headers];sh.getRange(`A2:${last}501`).format.font={name:'Arial',size:11,color:navy};sh.getRange(`A2:${last}501`).format.rowHeight=23;sh.getRange(`A2:${last}501`).format.verticalAlignment='center';headers.forEach((_,i)=>sh.getRange(`${String.fromCharCode(65+i)}1:${String.fromCharCode(65+i)}501`).format.columnWidth=widths[i]);const t=sh.tables.add(`A1:${last}501`,true,tableName);t.showFilterButton=true;head(sh,`A1:${last}1`);sh.freezePanes.freezeRows(1);return sh;}
const ap=table('Randevular',['Tarih','Saat','Müşteri','Telefon','Hizmet','Ücret (TRY)','Durum','Not'],[15,11,25,20,25,18,19,42],'Appointments');
const cu=table('Müşteriler',['Müşteri','Telefon','E-posta','Son Ziyaret','Toplam Ziyaret','Harcama (TRY)','Not'],[25,20,32,17,21,21,42],'Customers');
const fi=table('Finans',['Gelir Tarihi','Gelir Açıklaması','Gelir Kategorisi','Gelir (TRY)','Gider Tarihi','Gider Açıklaması','Gider Kategorisi','Gider (TRY)'],[18,30,23,19,18,30,23,19],'Finance');
for(const [sh,ranges] of [[ap,['A2:A501']],[cu,['D2:D501']],[fi,['A2:A501','E2:E501']]])for(const r of ranges){sh.getRange(r).setNumberFormat('dd.mm.yyyy');sh.getRange(r).dataValidation={rule:{type:'whole',operator:'between',formula1:1,formula2:2958465}};}
ap.getRange('B2:B501').setNumberFormat('hh:mm');ap.getRange('B2:B501').dataValidation={rule:{type:'decimal',operator:'between',formula1:0,formula2:0.99999999}};
for(const [sh,ranges] of [[ap,['F2:F501']],[cu,['F2:F501']],[fi,['D2:D501','H2:H501']]])for(const r of ranges){sh.getRange(r).setNumberFormat('#,##0.00');sh.getRange(r).dataValidation={rule:{type:'decimal',operator:'greaterThanOrEqual',formula1:0}};}
cu.getRange('E2:E501').dataValidation={rule:{type:'whole',operator:'greaterThanOrEqual',formula1:0}};
ap.getRange('G2:G501').dataValidation={rule:{type:'list',values:['Bekliyor','Onaylandı','Tamamlandı','İptal']}};
ap.getRange('G2:G501').conditionalFormats.addCustom('G2="İptal"',{fill:'#FDE2E1',font:{color:'#991B1B'}});
ap.getRange('D2:D501').setNumberFormat('@');cu.getRange('B2:B501').setNumberFormat('@');
const dash=sheets.Dashboard;dash.getRange('A1:H26').format.columnWidth=18;dash.mergeCells('A2:H2');dash.getRange('A2').values=[['MexAy Business Excel Kit']];dash.getRange('A2').format.font={name:'Arial',size:20,bold:true,color:navy};dash.mergeCells('A3:H3');dash.getRange('A3').values=[['Tüm kayıtların özeti. Para tutarları TRY.']];dash.getRange('A3').format.font={name:'Arial',size:11,italic:true,color:'#6B7280'};
const cards=[['A5','Toplam Randevu','=COUNTIF(\'Randevular\'!A2:A501,"<>")'],['C5','Bekleyen','=B13'],['E5','Onaylanan','=B14'],['G5','Tamamlanan','=B15'],['A8','Toplam Müşteri','=COUNTIF(\'Müşteriler\'!A2:A501,"<>")'],['C8','Toplam Gelir','=SUM(\'Finans\'!D2:D501)'],['E8','Toplam Gider','=SUM(\'Finans\'!H2:H501)'],['G8','Net Kazanç','=C9-E9']];
for(const [pos,label,f] of cards){const col=pos[0],row=Number(pos.slice(1)),next=String.fromCharCode(col.charCodeAt(0)+1);dash.mergeCells(`${col}${row}:${next}${row}`);dash.mergeCells(`${col}${row+1}:${next}${row+1}`);dash.getRange(pos).values=[[label]];dash.getRange(`${col}${row}:${next}${row}`).format={fill:light,font:{name:'Arial',size:11,bold:true,color:navy}};dash.getRange(`${col}${row+1}`).formulas=[[f]];dash.getRange(`${col}${row+1}`).format.font={name:'Arial',size:18,bold:true,color:navy};if(row===8&&col!=='A')dash.getRange(`${col}${row+1}`).setNumberFormat('#,##0.00');}
dash.getRange('A12:B16').values=[['Durum','Adet'],['Bekliyor',null],['Onaylandı',null],['Tamamlandı',null],['İptal',null]];head(dash,'A12:B12');dash.getRange('B13:B16').formulas=['Bekliyor','Onaylandı','Tamamlandı','İptal'].map(x=>[`=COUNTIF('Randevular'!G2:G501,"${x}")`]);
const chart=dash.charts.add('bar',dash.getRange('A12:B16'));chart.title='Randevu Durumu';chart.titleTextStyle.typeface='Arial';chart.titleTextStyle.fontSize=13;chart.hasLegend=false;chart.xAxis={axisType:'textAxis',textStyle:{typeface:'Arial',fontSize:11}};chart.yAxis={numberFormatCode:'0',numberFormatSourceLinked:false,textStyle:{typeface:'Arial',fontSize:11}};chart.series.items[0].fill=orange;chart.setPosition('D12','H24');
dash.mergeCells('A26:H26');dash.getRange('A26').values=[['Kapasite: her giriş sayfasında 500 kayıt (2-501. satırlar).']];dash.getRange('A26').format.font={name:'Arial',size:11,italic:true,color:'#6B7280'};
const st=sheets.Ayarlar;st.getRange('A1:B9').values=[['Alan','Değer'],['İşletme Adı',''],['Telefon',''],['E-posta',''],['Adres',''],['Çalışma Başlangıcı',9/24],['Çalışma Bitişi',18/24],['Para Birimi','TRY'],['Pazar','Kapalı']];st.getRange('A1:A9').format.columnWidth=30;st.getRange('B1:B9').format.columnWidth=46;head(st,'A1:B1');st.getRange('B2:B9').format.fill='#FFF3D3';st.getRange('B6:B7').setNumberFormat('hh:mm');st.mergeCells('A11:F11');st.getRange('A11').values=[['Çalışma saatleri bilgi amaçlıdır; randevuları otomatik engellemez.']];st.mergeCells('A12:F12');st.getRange('A12').values=[['Bu sürümde hesaplamaların para birimi TRY olarak sabittir.']];
const hi=sheets['Hızlı Başlangıç'];hi.getRange('A1:A16').format.columnWidth=105;hi.getRange('A1').values=[['Hızlı Başlangıç']];hi.getRange('A1').format.font={name:'Arial',size:17,bold:true,color:navy};const steps=['Ayarlar sayfasına işletme bilgilerinizi yazın.','Müşteriler sayfasına kayıtları ekleyin. Telefon alanı metindir.','Randevular: tarih, saat, müşteri, hizmet, ücret ve durumu girin.','Tarihi 05.10.2026, saati 10:00 biçiminde Excel tarih/saat değeri olarak girin.','Finans: gerçekleşen gelirleri ve giderleri bu sayfaya ayrıca yazın.','Randevu ücreti otomatik gelir değildir; Dashboard Finans kayıtlarını toplar.','Müşteri ziyaret ve harcama özetleri bu sürümde elle güncellenir.','Her giriş tablosu 500 kayıt içindir. 501. satırdan sonra özetlere veri dahil edilmez.','Kapasiteyi artırmak için tabloları, özet formüllerini ve doğrulama aralıklarını birlikte uzatın.','Çalışma saatleri ve Pazar ayarı yalnızca işletme bilgisi olarak saklanır.','Dosya boş başlar; örnek müşteri veya gelir içermez.','Excel hesaplamasını Otomatik tutun; önemli değişikliklerden sonra yedek alın.','Tek işletme lisansı. Dahil edilen dosyaların yeniden satışı veya dağıtımı yasaktır.'];hi.getRange('A3:A15').values=steps.map(x=>[x]);hi.getRange('A3:A15').format.wrapText=true;hi.getRange('A3:A15').format.rowHeight=40;
// Recalculate with changed inputs at the first, middle and final supported rows.
for(const row of [2,250,501]){ap.getRange(`A${row}:H${row}`).values=[[new Date('2026-10-05T00:00:00Z'),10/24,'TEST','05000000000','Hizmet',750.25,'Onaylandı',null]];cu.getRange(`A${row}`).values=[['TEST']];fi.getRange(`D${row}`).values=[[750.25]];fi.getRange(`H${row}`).values=[[100.10]];wb.recalculate();assert.equal(dash.getRange('A6').values[0][0],1);assert.equal(dash.getRange('E6').values[0][0],1);assert.ok(Math.abs(dash.getRange('G9').values[0][0]-650.15)<1e-8);ap.getRange(`G${row}`).values=[['İptal']];assert.equal(dash.getRange('E6').values[0][0],0);assert.equal(dash.getRange('B16').values[0][0],1);ap.getRange(`A${row}:H${row}`).clear({applyTo:'contents'});cu.getRange(`A${row}`).clear({applyTo:'contents'});fi.getRange(`D${row}`).clear({applyTo:'contents'});fi.getRange(`H${row}`).clear({applyTo:'contents'});}
wb.recalculate();assert.equal(dash.getRange('A6').values[0][0],0);assert.equal(dash.getRange('G9').values[0][0],0);
await fs.mkdir(out,{recursive:true});await fs.mkdir(`${out}/../qa`,{recursive:true});
const inspection=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:100},maxChars:3000});await fs.writeFile(`${out}/../qa/formula-scan.jsonl`,inspection.ndjson);
for(const [name,range] of [['Dashboard','A1:H27'],['Randevular','A1:H8'],['Müşteriler','A1:G8'],['Finans','A1:H8'],['Ayarlar','A1:F14'],['Hızlı Başlangıç','A1:A16']]){const blob=await wb.render({sheetName:name,range,scale:1,format:'png'});await fs.writeFile(`${out}/../qa/${names.indexOf(name)}.png`,new Uint8Array(await blob.arrayBuffer()));}
const file=await SpreadsheetFile.exportXlsx(wb);await file.save(`${out}/MexAy_Business_Management_Kit.xlsx`);console.log('Workbook built; first/middle/final row recalculation and empty-state checks passed.');
